# Generated by Django 5.2.8 on 2025-12-13 05:28

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places_app", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
