# Generated by Django 5.2.8 on 2025-12-16 16:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
    ]
