# Generated by Django 5.2.8 on 2025-12-16 17:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_allow_blank_description_long"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
