# Generated by Django 5.2.8 on 2025-12-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_rename_description_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="image",
            index=models.Index(
                fields=["position"], name="places_imag_positio_b2104b_idx"
            ),
        ),
    ]
