# Generated by Django 5.2.8 on 2025-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_add_position_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="Название"
            ),
        ),
    ]
